### ISSUE TITLE
Adding bootstrap.min.css file from Bootstrap 3 library causes an error.

### ISSUE THREAD

**Issue by pkrukowski** [stedekay/SpraedPDFGeneratorBundle#22]
Adding bootstrap.min.css file from Bootstrap 3 library causes an error:

The exit status code '1' says something went wrong:
stderr: "Exception in thread "main" java.lang.ClassCastException: org.xhtmlrenderer.render.BlockBox cannot be cast to org.xhtmlrenderer.newtable.TableBox
at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:127)
at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:139)
at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:139)
at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:139)
at org.xhtmlrenderer.layout.BoxCollector.collect(BoxCollector.java:46)
at org.xhtmlrenderer.layout.Layer.paint(Layer.java:314)
at org.xhtmlrenderer.pdf.ITextRenderer.paintPage(ITextRenderer.java:384)
at org.xhtmlrenderer.pdf.ITextRenderer.writePDF(ITextRenderer.java:348)
at org.xhtmlrenderer.pdf.ITextRenderer.createPDF(ITextRenderer.java:315)
at org.xhtmlrenderer.pdf.ITextRenderer.createPDF(ITextRenderer.java:280)
at com.spraed.flyingsaucer.PDFGenerator.main(PDFGenerator.java:114)
"
stdout: ""
command: java -Djava.awt.headless=true -jar "/somepath/vendor/spraed/pdf-generator-bundle/Spraed/PDFGeneratorBundle/Resources/java/spraed-pdf-generator.jar" --html "/tmp/tmp551be503b08b4." --pdf "/tmp/output551be503b084e.pdf" --encoding UTF-8.

**Comment by stedekay** [comment]
Can you show me your template?

**Comment by babichalex** [comment]
Hey, I've faced with the same problem. I'm using Symfony2 assets to load bootstrap.min.css. My template looks like this - https://gist.github.com/babichalex/3875d0ce6d7b48aeaf7e

**Comment by Ferror** [comment]
I have the same problem. all assets works fine, but bootstrap.css cause problem

**Comment by stedekay** [comment]
Sorry that I never answered anymore to this issue.
This library was maintained poorly by me the last couple years due to spending less time for Open Source, more for my family (and this priority will also exist in the future).

If this issue still exists, please open a new issue and I will try my best to help out.
